Adds extension methods for Task wrapped Result and Option type assertions
RyanMarcotte/Functional.Utilities pull request #9
Opened 2020-09-30 20:39 UTC by Justin-Cooney

This PR adds extension methods that provide assertions for both `Task<Option<T>>` and `Task<Result<TSuccess, TFailure>>`.

Example `Task<Option<T>>` assertion:
```C#
Task.FromResult(Option.Some(VALUE))
    .Should()
    .HaveValue()
    .AndValue(v => v.Should().Be(VALUE)))
```

Example `Task<Result<TSuccess, TFailure>>` assertion:
```C#
Task.FromResult(Result.Failure<int, Exception>(new Exception(VALUE)))
    .Should()
    .BeFaulted()
    .AndFailureValue(e => e.Message.Should().Be("Exception")))
```

2020-09-30 21:03 UTC, RyanMarcotte requested changes
Looks good!  Please add documentation to the `README.md` file for these new extension methods.

2020-09-30 21:35 UTC, Justin-Cooney commented
Documentation has been added to the ReadMe for `Task<Option<T>>` and `Task<Result<TSuccess, TFailure>>`

2020-10-01 17:26 UTC, ChrisDusyk submitted a review, later dismissed

2020-10-01 18:23 UTC, RyanMarcotte commented
Documentation looks good!  Thanks for writing that up.

2020-10-01 18:25 UTC, RyanMarcotte commented
Please bump the minor version number and add release notes in the `Functional.Primitives.FluentAssertions` project's properties @Justin-Cooney .  I am OK with merging this in before the Union stuff as there is likely some more work to be done there.

Once the version number is bumped, this PR is good to go.  I can then cut a release later today.

2020-10-05 17:29 UTC, RyanMarcotte approved these changes

2020-10-05 17:31 UTC, merged